### ISSUE TITLE
lighty: Schema is not available for http.org.openroadm.device.rev200529

### ISSUE THREAD

**Issue by purplezimmermann** [purplezimmermann/opendaylight-transportpce#6]
When adding a new `config/network-topology:network-topology/topology/topology-netconf/node/...` with OpenROADM 7.1 capabilities, the following error happens:

```java
... OpenROADM version 7.1.0 node - Creating Mapping Data
ERROR [opendaylight-cluster-data-notification-dispatcher-99] (DataTreeChangeListenerActor.java:85) - member-1-shard-topology-operational: Error notifying listener org.opendaylight.mdsal.binding.dom.adapter.BindingDOMDataTreeChangeListenerAdapter@5eac2d31
org.opendaylight.mdsal.binding.dom.codec.api.MissingSchemaForClassException: Schema is not available for interface org.opendaylight.yang.gen.v1.http.org.openroadm.device.rev200529.org.openroadm.device.container.OrgOpenroadmDevice
        at org.opendaylight.mdsal.binding.dom.codec.impl.DataContainerCodecContext.childNullException(DataContainerCodecContext.java:211)
        at org.opendaylight.mdsal.binding.dom.codec.impl.DataContainerCodecContext.childNonNull(DataContainerCodecContext.java:188)
        at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.createDataTreeChildContext(SchemaRootCodecContext.java:207)
        at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$1.load(SchemaRootCodecContext.java:61)
        at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$1.load(SchemaRootCodecContext.java:58)
...
```

And no port mapping data is created for the new device under `config/transportpce-portmapping:network/...`

**Comment by purplezimmermann** [comment]
Resolved by #7
